name: NodeJS with Django

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.10]  # Include Python 3.8 and 3.10 to test compatibility
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Django and Compatibility Fix
      run: |
        if [[ "${{ matrix.python-version }}" == "3.8" ]]; then
          sed -i 's/Django==5.0.1/Django==4.2.x/' requirements.txt
        fi
        pip install -r requirements.txt

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Node Dependencies
      run: |
        npm install

    - name: Run Grunt
      run: |
        grunt

    - name: Run Tests
      run: |
        npm test
        python manage.py test  # Run Django tests

    - name: Check Linting
      run: |
        npm run lint
