name: NodeJS with Grunt

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # Cache npm modules to speed up workflow

    - name: Install Dependencies
      run: |
        npm install

    - name: Run Grunt
      run: |
        grunt

    - name: Run Tests
      run: |
        npm test  # Ensure there's a test script in package.json for running tests

    - name: Check Linting
      run: |
        npm run lint  # Ensure there's a lint script in package.json or install linters like ESLint
